FROM debian:stretch
SHELL ["/bin/bash", "-c"]

# dependencies
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y \
    automake pkg-config libtool
RUN apt-get install -y \
    python-dev python-pip python-virtualenv

# curl is a better tool
RUN apt-get install -y curl
# for coveralls
RUN apt-get -y install git

RUN useradd --home-dir /home/chaum --create-home --shell /bin/bash --skel /etc/skel/ chaum
ARG owner_name
ARG repo_name
COPY ./downloads/bitcoin-0.14.2-x86_64-linux-gnu.tar.gz /home/chaum
COPY ./${owner_name}/ /home/chaum
RUN chown -R chaum:chaum /home/chaum
USER chaum

# copy node software from the host and install
WORKDIR /home/chaum
RUN tar xaf bitcoin-0.14.2-x86_64-linux-gnu.tar.gz
ENV PATH "/home/chaum/bitcoin-0.14.2/bin:${PATH}"
RUN bitcoind --help 1>/dev/null || false

# install script
RUN ls -la .
RUN echo ${repo_name}
WORKDIR ${repo_name}
RUN ./install.sh
RUN source jmvenv/bin/activate && ./test/run_tests.sh
