FROM fedora:26
SHELL ["/bin/bash", "-c"]

# dependencies
RUN dnf -y groups install 'Development tools'
RUN dnf -y install \
    autoconf libtool pkgconfig \
    python-devel python-pip python2-virtualenv

# needed for build time
# https://stackoverflow.com/questions/34624428/g-error-usr-lib-rpm-redhat-redhat-hardened-cc1-no-such-file-or-directory
RUN dnf -y install redhat-rpm-config

RUN useradd --home-dir /home/chaum --create-home --shell /bin/bash --skel /etc/skel/ chaum
ARG owner_name
ARG repo_name
COPY ./downloads/bitcoin-0.14.2-x86_64-linux-gnu.tar.gz /home/chaum
COPY ./${owner_name}/ /home/chaum
RUN chown -R chaum:chaum /home/chaum
USER chaum

# copy node software from the host and install
COPY ./downloads/bitcoin-0.14.2-x86_64-linux-gnu.tar.gz /home/chaum
WORKDIR /home/chaum
RUN tar xaf bitcoin-0.14.2-x86_64-linux-gnu.tar.gz
ENV PATH "/home/chaum/bitcoin-0.14.2/bin:${PATH}"
RUN bitcoind --help 1>/dev/null || false

# install script
RUN ls -la .
RUN echo ${repo_name}
WORKDIR ${repo_name}
RUN ./install.sh
RUN source jmvenv/bin/activate && ./test/run_tests.sh
