FROM centos:7
SHELL ["/bin/bash", "-c"]

# dependencies
RUN yum -y groups install 'Development tools'
RUN yum -y install epel-release && \
    yum -y update
RUN yum -y install \
    python-devel python2-pip python-virtualenv
# for coveralls
RUN yum -y install git

RUN useradd --home-dir /home/chaum --create-home --shell /bin/bash --skel /etc/skel/ chaum
ARG owner_name
ARG repo_name
COPY ./downloads/bitcoin-0.14.2-x86_64-linux-gnu.tar.gz /home/chaum
COPY ./${owner_name}/ /home/chaum
RUN chown -R chaum:chaum /home/chaum
USER chaum

# copy node software from the host and install
COPY ./downloads/bitcoin-0.14.2-x86_64-linux-gnu.tar.gz /home/chaum
WORKDIR /home/chaum
RUN tar xaf bitcoin-0.14.2-x86_64-linux-gnu.tar.gz
ENV PATH "/home/chaum/bitcoin-0.14.2/bin:${PATH}"
RUN bitcoind --help 1>/dev/null || false

# install script
RUN ls -la .
RUN echo ${repo_name}
WORKDIR ${repo_name}
RUN ./install.sh
RUN source jmvenv/bin/activate && ./test/run_tests.sh
